# Jekyll settings
#
title: Projet Ornithorynque
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Un kamishibaï réalisé dans la classe de CP de Mme Marckert, porté en ligne.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.bac-a-sable.eu" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
nav_direction: vertical # vertical, horizontal 
image_dir: "assets/images"
sound_source: ""
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

